### ISSUE TITLE
SYSTEMC 无法提取

### ISSUE THREAD

**Issue by dk000000000** [satan53x/SExtractor#30]
Traceback (most recent call last):
  File "D:\汉化工具\SExtractor-main\main\thread.py", line 18, in run
    self.window.extractFileThread()
  File "D:\汉化工具\SExtractor-main\main\mainWindow.py", line 198, in extractFileThread
    mainExtractBin(args)
  File "D:\汉化工具\SExtractor-main\./src\main_extract_bin.py", line 82, in mainExtractBin
    mainExtract(args, parse, initDone)
  File "D:\汉化工具\SExtractor-main\./src\main_extract.py", line 641, in mainExtract
    parseImp()
  File "D:\汉化工具\SExtractor-main\./src\main_extract_bin.py", line 61, in parse
    var.parseImp(var.content, var.listCtrl, dealOnce)
  File "D:\汉化工具\SExtractor-main\./src\extract_SystemC.py", line 13, in parseImp
    re.compile(rb'^[A-Za-z/\*]', rb'^$')
  File "C:\Users\Learner G\anaconda3\Lib\re\__init__.py", line 227, in compile
    return _compile(pattern, flags)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Learner G\anaconda3\Lib\re\__init__.py", line 287, in _compile
    if flags & T:
       ~~~~~~^~~
TypeError: unsupported operand type(s) for &: 'bytes' and 'RegexFlag'

**Comment by satan53x** [comment]
更新了，再试试呢

**Comment by satan53x** [comment]
不过现在这个引擎一般都是直接正则了，不需要单独引擎。这个是早期写的。

**Comment by dk000000000** [comment]
Traceback (most recent call last):
  File "D:\汉化工具\SExtractor-main\main\thread.py", line 18, in run
    self.window.extractFileThread()
  File "D:\汉化工具\SExtractor-main\main\mainWindow.py", line 198, in extractFileThread
    mainExtractBin(args)
  File "D:\汉化工具\SExtractor-main\./src\main_extract_bin.py", line 82, in mainExtractBin
    mainExtract(args, parse, initDone)
  File "D:\汉化工具\SExtractor-main\./src\main_extract.py", line 641, in mainExtract
    parseImp()
  File "D:\汉化工具\SExtractor-main\./src\main_extract_bin.py", line 61, in parse
    var.parseImp(var.content, var.listCtrl, dealOnce)
  File "D:\汉化工具\SExtractor-main\./src\extract_SystemC.py", line 23, in parseImp
    if any(pattern.match(var.lineData) for pattern in regSkip):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\汉化工具\SExtractor-main\./src\extract_SystemC.py", line 23, in <genexpr>
    if any(pattern.match(var.lineData) for pattern in regSkip):
           ^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'match'

**Comment by dk000000000** [comment]
感谢，问题以解决
