### ISSUE TITLE
不管选择何种翻译方式都会报错

### ISSUE THREAD

**Issue by PantsuDango** [satan53x/SExtractor#90]
项目选择翻译器：sakura-009
```bash
[06-16 12:20:14][WARNING]未找到文本插件: (project_dir)text_common_example，跳过该插件
[06-16 12:20:14][INFO]加载插件"通用-译后常规修复"...
RetryError[<Future at 0x21a736806b0 state=finished raised ConnectError>]
Traceback (most recent call last):
  File "httpx\_transports\default.py", line 69, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 373, in handle_async_request
  File "httpcore\_async\connection_pool.py", line 216, in handle_async_request
  File "httpcore\_async\connection_pool.py", line 196, in handle_async_request
  File "httpcore\_async\http_proxy.py", line 207, in handle_async_request
  File "httpcore\_async\connection.py", line 99, in handle_async_request
  File "httpcore\_async\connection.py", line 76, in handle_async_request
  File "httpcore\_async\connection.py", line 122, in _connect
  File "httpcore\_backends\auto.py", line 30, in connect_tcp
  File "httpcore\_backends\anyio.py", line 114, in connect_tcp
  File "contextlib.py", line 158, in __exit__
  File "httpcore\_exceptions.py", line 14, in map_exceptions
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tenacity\_asyncio.py", line 61, in __call__
  File "GalTransl\ConfigHelper.py", line 168, in _availablityChecker
  File "httpx\_client.py", line 1801, in get
  File "httpx\_client.py", line 1574, in request
  File "httpx\_client.py", line 1661, in send
  File "httpx\_client.py", line 1689, in _send_handling_auth
  File "httpx\_client.py", line 1726, in _send_handling_redirects
  File "httpx\_client.py", line 1763, in _send_single_request
  File "httpx\_transports\default.py", line 372, in handle_async_request
  File "contextlib.py", line 158, in __exit__
  File "httpx\_transports\default.py", line 86, in map_httpcore_exceptions
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "GalTransl\__main__.py", line 32, in worker
  File "asyncio\runners.py", line 194, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 685, in run_until_complete
  File "GalTransl\Runner.py", line 139, in run_galtransl
  File "GalTransl\ConfigHelper.py", line 190, in checkAvailablity
  File "tenacity\_asyncio.py", line 142, in async_wrapped
  File "tenacity\_asyncio.py", line 58, in __call__
  File "tenacity\_asyncio.py", line 110, in iter
  File "tenacity\_asyncio.py", line 78, in inner
  File "tenacity\__init__.py", line 411, in exc_check
tenacity.RetryError: RetryError[<Future at 0x21a736806b0 state=finished raised ConnectError>]
请按任意键继续. . .
```

**Comment by PantsuDango** [comment]
发错地方了，不好意思！~
